version: "3"

services:

  application:
    build: 
      context: .
    ports:
      - 8000:8000
    container_name: website-hook-clone-application
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '2' 
          memory: 512M 

  worker:
    build: 
      context: .
    container_name: website-hook-clone-worker
    command: "php artisan queue:work"
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.5' 
          memory: 512M 
  
  worker2:
    build: 
      context: .
    container_name: website-hook-clone-worker-2
    command: "php artisan queue:work"
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.5' 
          memory: 512M 

networks:
  default:
    driver: bridge